src/DressApp/urls.py
from django.urls import path
from . import views

app_name = 'DressApp' # これは、他のテンプレートからviewを呼び出す際に用いるが、この記事では無関係
urlpatterns = [
    path('', views.index, name='index'), #urlに/DressAppと入力するとviews.pyのindex関数が呼び出される。
    #path('chat', views.chat, name='chat'), #urlに/DressAppと入力するとviews.pyのindex関数が呼び出される。
    path('ajax-file-send/', views.ajax_file_send, name='ajax_file_send'),
    path('click_cut/', views.click_cut, name="click_cut"),
    path('select_clothes/', views.select_clothes, name='select_clothes'),
    path('showall/', views.showall, name='showall'),
    path('upload/', views.upload, name='upload')
]

src/app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
app_name = 'app'
urlpatterns = [
    path('chat',views.index,name='chat'),
    path('customer',views.send_clother,name='clother')
]

src/mainproject/urls.py
from django.contrib import admin
from django.urls import include, path
# auth.viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('app', include('app.urls')),
    path('admin/', admin.site.urls),

    # accounts.urlsへのURLパターンを追加
    path('', include('accounts.urls')),

    # topページ
    path('', include('top.urls')),

    # パスワードリセットのためのURLパターン
    # PasswordResetConfirmViewがプロジェクトのurls.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
           template_name = "password_reset.html"),
         name ='password_reset'),
    
    # メール送信完了ページ
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
           template_name = "password_reset_sent.html"),
         name ='password_reset_done'),
    
    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
           template_name = "password_reset_form.html"),
         name ='password_reset_confirm'),
    
    # パスワードリセット完了ページ
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
           template_name = "password_reset_done.html"),
         name ='password_reset_complete'),
    
    # dress.urlsへのURLパターンを追加
    path('dress/', include('DressApp.urls')),
]

src/DressApp/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
# このモデルは
# 人の名前
# 身長
# クライアントから位受け取った画像のパス(mediaからのパス)
# 背景削除画像のパス(mediaからのパス)と
# 人物部位セグメンテーション画像のパス(srcからdress_lib/dress_lib/materials/part_segms/画像ファイルまでのパス)
# 骨格情報を持つjsonファイルのパス(srcからdress_lib/dress_lib/materials/skeleton_jsons/jsonファイルまでのパス)
# といった入力されたものから画像処理を行なった情報までをdbに登録するためのもの
class Human_body(models.Model):
    # human_nameプロパティは最大100文字でユニークの文字列
    human_name = models.CharField(max_length=100)#, unique=True)#人の名前
    height = models.IntegerField(default=0,validators=[MinValueValidator(1), MaxValueValidator(250)])#身長
    picture = models.ImageField(upload_to="human_img/",blank=True,null=True)#クライアントから受け取った画像のパス(mediaからのパス)
    
    cut_image_path = models.URLField(default='none_path',max_length=1000)#背景削除画像のパス(mediaからのパス)
    part_segm_path = models.URLField(default='none_path',max_length=1000)#人物部位セグメンテーション画像のパス(srcからdress_lib/dress_lib/materials/part_segms/画像ファイルまでのパス)
    skeleton_json_path = models.URLField(default='none_path',max_length=1000)#骨格情報を持つjsonファイルのパス(srcからdress_lib/dress_lib/materials/skeleton_jsons/jsonファイルまでのパス)
    def __str__(self):
        return self.id

class Human_clothes(models.Model):
    human_id = models.IntegerField(default=0)
    part_clothes = models.IntegerField(default=0)
    clothes_name = models.CharField(max_length=100)
    match_clothes_path = models.URLField(default='none_path',max_length=1000)

src/DressApp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.core import serializers
from django.http.response import JsonResponse
from .dress_lib import image_cut
from .dress_lib.change_clothes_lib import clothes_on_top

from .form import ImageForm
from .models import Human_body
from .models import Human_clothes

import cv2
import matplotlib.pyplot as plt
import json
import time
import numpy as np
import os

use_id = None # intデータが必ず入る

#クライアントにHTMLデータを渡す
def index(request):
    #return HttpResponse("Hello World")
    images =  Human_body.objects.all()
    form = ImageForm()
    context = {'form':form,'images':images}
    global use_id
    use_id = None
    return render(request, 'dressed.html', context)

def click_cut(request):
    global use_id
    use_id = request.POST.get('use_id')
    d={
        "chat":"データを送信しました",
    }
    return JsonResponse(d)

def ajax_file_send(request):#ajaxでクライアントから画像をもらう
    start = time.time()
    topProc_start = time.time()
    
    #file = request.FILES['picture']
    if request.method == "POST":
        #クライアントから受け取ったモデルhuman_bodyに沿うデータと画像を引数にImageFormクラスを作る
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():# 入力された全てのデータが適切だったら
            #human_body = Human_body.objects.create(...)
            #form.save()# フォームクラス(ImageForm)の適切なデータ(id,name,height,picture)をdbに保存する

            # (id,name,height,picture)をdbに保存する
            human_body = Human_body()#modelクラスをインスタンス化
            human_body.human_name = request.POST['human_name']#human_nameを入れる
            human_body.height = request.POST['height']#heightを入れる
            human_body.picture = request.FILES['picture']#画像データを入れる
            human_body.save()#保存する
            with open("./DressApp/log.txt", mode='w') as f:# python側の処理が見えるようにログファイルに書き込み
                f.write("form.is_valid() = True")
                f.write("\n")
                f.write(str(form.cleaned_data))#formを介したdbへの追加方法だと、file名が重複変更前になる
                f.write("\n")
                f.write(str(human_body.id))# idはstr型に変換しないと書き込みエラー
                f.write("\n")
                f.write(human_body.human_name)
                f.write("\n")
                f.write(human_body.height)
                f.write("\n")
                f.write(str(human_body.picture).split('/')[1])
                f.write("\n")
                f.write(str(type(human_body.picture)))
                f.write("\n")
                '''all = Human_body.objects.all()
                for one in all:
                    f.write(one.human_name)
                    f.write(" , ")
                    f.write(str(one.height))
                    f.write(" , ")
                    f.write(str(one.picture))
                    f.write(" , ")
                    f.write(str(one.id))
                    f.write("\n")'''

            input_img_path = "./media/"+str(human_body.picture)# mediaディレクトリからのパスにする
            filename = str(human_body.picture).split('/')[1]# human_img/xxxからファイル名xxxを抽出

            topProc_time = time.time() - topProc_start
            with open("./DressApp/log.txt", mode='a') as f:# python側の処理が見えるようにログファイルに書き込み
                f.write("topProc_time:{0}".format(topProc_time) + "[sec]")
                f.write("\n")
            filename,timestr,actual_img,human_segm,candidate_json = image_cut.image_cut(filename,input_img_path,int(human_body.height))# 画像処理開始
            bottomProc_start = time.time()
            with open("./DressApp/log.txt", mode='a') as f:# python側の処理が見えるようにログファイルに書き込み
                f.write(timestr)
                f.write("\n")
            #human_segm = cv2.imread("./DressApp/dress_lib/materials/part_segms/test.png")#テストhuman_segm
            #actual_img = cv2.imread("./media/cut_images/test.png")#テストactual_img
            #candidate_json = '["foo",{"baz":["baz",null,1.0,34]}]'#テストcandidate_json

            #骨格情報JSONデータを保存
            skeleton_path='./DressApp/dress_lib/materials/skeleton_jsons/'+filename.split('.')[0]+".json"
            with open('./DressApp/dress_lib/materials/skeleton_jsons/'+filename.split('.')[0]+".json", 'w') as fp:
                json.dump(candidate_json, fp, indent=4, ensure_ascii=False)
            
            #人物部位セグメンテーション画像を保存
            human_segm_path="./DressApp/dress_lib/materials/part_segms/"+filename
            cv2.imwrite("./DressApp/dress_lib/materials/part_segms/"+filename,human_segm)
            #背景削除画像を保存
            actual_img_path="/media/cut_images/"+filename
            cv2.imwrite("./media/cut_images/"+filename,actual_img)

            human_body.cut_image_path = actual_img_path#背景切り抜き画像があるパス
            human_body.part_segm_path = human_segm_path#人物部位セグム画像があるパス
            human_body.skeleton_json_path = skeleton_path#骨格jsonがあるパス
            human_body.save()#更新
            with open("./DressApp/log.txt", mode='a') as f:# python側の処理が見えるようにログファイルに書き込み
                f.write(str(human_body.id))
                f.write("\n")
                f.write(human_body.cut_image_path)
                f.write("\n")
                f.write(human_body.part_segm_path)
                f.write("\n")
                f.write(human_body.skeleton_json_path)
                f.write("\n")
                f.write(timestr)
                f.write("\n")

            
            images =  Human_body.objects.all()
            json_encode = list(images.values())
            #下でもquerysetからjsonで扱える形式にできる
            #images =  Human_body.objects.all()
            #images = serializers.serialize('json', Human_body.objects.all())
            #images = json.loads(images)
            d = {
                "queryset":json_encode
            }
            bottom_time = time.time() - bottomProc_start
            elapsed_time = time.time() - start
            with open("./DressApp/log.txt", mode='a') as f:# python側の処理が見えるようにログファイルに書き込み
                f.write("bottom_time:{0}".format(bottom_time) + "[sec]")
                f.write("\n")
                f.write("elapsed_time:{0}".format(elapsed_time) + "[sec]")
                f.write("\n")
            return JsonResponse(d)
        else:
            with open("./DressApp/log.txt", mode='w') as f:
                f.write("form.is_valid() = False")
                f.write(str(form.errors))
    else:
        form = ImageForm()

    context = {'form':form}
    d = {
        "img_url":"/static/app_images/dress_img/3_40_haikei.png"
    }
    return JsonResponse(d)

def select_clothes(request):
    part_clothes = int(request.POST.get('part_clothes'))
    clothes_name = request.POST.get('clothes_name')
    send_use_id = request.POST.get('use_id')
    global use_id
    d={
        "chat":"データを送信できましたが、処理中にエラーが起きました",
        "flag":"failure",
    }
    if send_use_id == use_id:# 不整合性回避
        human_body =  Human_body.objects.get(id=use_id)#use_idでデータベースからHuman_bodyのデータを取得
        human_name = human_body.human_name#human_nameを取得
        height = human_body.height#heightを取得
        picture_path = str(human_body.picture)#pictureを取得
        cut_image_path = human_body.cut_image_path#cut_image_pathを取得
        part_segm_path = human_body.part_segm_path#part_segm_pathを取得
        skeleton_json_path = human_body.skeleton_json_path#skeleton_json_pathを取得
        # 既に着せ替えたことがあるデータかどうかを確かめる
        already_list = Human_clothes.objects.all().filter(human_id=use_id, part_clothes=part_clothes, clothes_name=clothes_name)
        already_count = already_list.count()# 既に着せ替えたことがあるデータの数
        if already_count == 0:# 既に着せ替えたことがあるデータがないなら
            actual_img = cv2.imread("."+cut_image_path,-1)
            human_segm = cv2.imread(part_segm_path,0)
            with open(skeleton_json_path) as f:
                candidate_txt = json.load(f)#strになる 元々dict型にするメソッドだが、dictになるjsonデータでないと、str型になる
                print(type(candidate_txt))
                candidate = json.loads(candidate_txt)#listになる
                print(type(candidate))
                candidate = np.array(candidate)#ndarrayになる
                print(type(candidate))
            result_img = None
            if part_clothes == 1:
                import traceback
                try:
                    result_img,brank_img = clothes_on_top.change(actual_img,human_segm,candidate,clothes_name)
                except:
                    with open("./DressApp/log.txt", mode='a') as f:# python側の処理が見えるようにログファイルに書き込み
                        f.write("---point error---\n")
                        f.write(str(traceback.format_exc()))
                        f.write("\n")
                    return JsonResponse(d)
            match_clothes_path = "./DressApp/dress_lib/materials/match_clothes/"+str(use_id)+"_"+str(part_clothes)+"_"+clothes_name+".png"
            cv2.imwrite(match_clothes_path,brank_img)

            human_clothes = Human_clothes()
            human_clothes.human_id = use_id
            human_clothes.part_clothes = part_clothes
            human_clothes.clothes_name = clothes_name
            human_clothes.match_clothes_path = match_clothes_path
            human_clothes.save()#保存する
        else:#着せ替えたことがあるなら、match_clothes_pathからbrank_imgを取得しすぐにmounting
            actual_img = cv2.imread("."+cut_image_path,-1)
            brank_img = cv2.imread(already_list[0].match_clothes_path,-1)
            result_img = clothes_on_top.mounting(actual_img,brank_img)
        
        cv2.imwrite("./media/dress_images/dress.png",result_img)
        d={
            "chat":"着せ替えを行いました",
            "flag":"success",
            "id":use_id,
            "human_name":human_name,
            "height":height,
            "picture_path":picture_path,
            "cut_image_path":cut_image_path,
            "part_segm_path":part_segm_path,
            "skeleton_json_path":skeleton_json_path,
            "result_img_path":"/media/dress_images/dress.png"
        }

    return JsonResponse(d)


def showall(request):
    images =  Human_body.objects.all()
    context = {'images':images}

src/DressApp/templates/backup_dress.html
<!DOCTYPE html>
{% load static %} <!-- settings.pyのstaticfileの設定を読み込む -->
<html>
    <head>
        <meta charset="utf-8">
        <title>dressed</title>
        <link href="{% static "appcss/dressed.css" %}" rel="stylesheet" type="text/css" media="screen and (min-width:376px)">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <link href="{% static "appcss/dressed.css" %}" rel="stylesheet" type="text/css" media="screen and (max-width:375px)">
    </head>
    <body>
        <div id="main_frame">
            <div id="sub_frame">
                <div id="sub_left">
                    <img src="{% static "app_images/dress_img/dress2.jpeg" %}" alt="no_img" id="dress_back">
                    <div id="user_img_box">
                        <img src="" alt="no_img" id="user_img" class="hide_flag">
                    </div>
                    <div class="icon">
                        <img src="{% static "app_images/dress_img/human.png" %}" alt="no_img" id="human_icon">
                    </div>
                </div>
                <div id="sub_right">
                    <div class="model"></div>
                    <div class="model_have">
                        <img src="{% static "app_images/dress_img/model_10.png" %}" alt="no_img" id="1.model_10" class="model_img">
                    </div>
                    <div class="model_have">
                        <img src="{% static "app_images/dress_img/model_9.png" %}" alt="no_img" id="1.model_9" class="model_img">
                    </div>
                    <div class="model_have">
                        <img src="{% static "app_images/dress_img/model_8.png" %}" alt="no_img" id="1.model_8" class="model_img">
                    </div>
                    <div class="model_have">
                        <img src="{% static "app_images/dress_img/model_7.png" %}" alt="no_img" id="1.model_7" class="model_img">
                    </div>
                    <div class="model_have">
                        <img src="{% static "app_images/dress_img/model_6.png" %}" alt="no_img" id="1.model_6" class="model_img">
                    </div>
                    <div class="model_have">
                        <img src="{% static "app_images/dress_img/model_5.png" %}" alt="no_img" id="1.model_5" class="model_img">
                    </div>
                    <div class="model_have">
                        <img src="{% static "app_images/dress_img/model_4.png" %}" alt="no_img" id="1.model_4" class="model_img">
                    </div>
                    <div class="model_have">
                        <img src="{% static "app_images/dress_img/model_2.png" %}" alt="no_img" id="1.model_2" class="model_img">
                    </div>
                    <div class="model_have">
                        <img src="{% static "app_images/dress_img/model_3.png" %}" alt="no_img" id="1.model_3" class="model_img">
                    </div>
                    <div class="model_have">
                        <img src="{% static "app_images/dress_img/model_0.jpeg" %}" alt="no_img" id="1.model_0" class="model_img">
                    </div>
                    <div class="model_have" id="down">
                        <img src="{% static "app_images/dress_img/model_1.png" %}" alt="no_img" id="1.model_1" class="model_img">
                    </div>
                </div>
            </div>
            <div id="asset_form" class="hide_flag">
                <div class="avater_icon">
                    <img src="{% static "app_images/dress_img/human_plus.png" %}" id="human_plus_icon">
                    <div class="avater_text">
                        New avater
                    </div>
                </div>
                <div class="avater_icon">
                    <img src="{% static "app_images/dress_img/human_already.png" %}" alt="no_img" id="human_already_icon">
                    <div class="avater_text">
                        Avaters
                    </div>
                </div>

                <div id="file_form" class="none_flag">
                    <form id="ajax-file-send" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>
                            <label for="id_human_name">Human name:</label>
                            <input type="text" name="human_name" maxlength="100" required="" id="id_human_name">
                        </p>
                        <p>
                            <label for="id_height">Height:</label>
                            <input type="number" name="height" value="0" required="" id="id_height"></p>
                        <p>
                            <label for="id_picture">Picture:</label>
                            <input type="file" name="picture" accept="image/*" id="id_picture"></p>
                        <!--<p>ファイル：<input type="file" id="uploadfile" name="uploadfile" value=""></p>-->
                        <p><input type="submit" name="submit"></p>
                    </form>
                    <!--
                    <form enctype="multipart/form-data" action="{% url 'DressApp:upload' %}" method="POST">
                        {% csrf_token %}
                        {{form.as_p}}
                        <input type="submit" value="Upload" id="f_b">
                    </form>-->
                    <!--
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token%}
                        {{ form.avator }}{{ form.avator.errors }}
                        <button type="submit" class="btn">Register</button>
                    </form>-->
                         
                    <div id="file_look">

                    </div>
                    <button class="kyanseru">キャンセル</button>
                </div>
                <div id="avater_select_form" class="none_flag">
                    <div id="select_img_contents">
                        {% for image in images %}
                        <div class="cut_img_contant">
                            <!--<img class="cut_img" src='{{ MEDIA_URL }}{{image.picture}}'>-->
                            <img class="cut_img" src='{{image.cut_image_path}}' id='{{image.id}}' onclick="click_cut_img(this)">
                            <h2 class="cut_img_name">{{ image.human_name }}</h2>
                        </div>
                        {% endfor %}
                    </div>
                    <button class="kyanseru">キャンセル</button>
                </div>
            </div>
            <div id="black_pocket">
                <div id="black_mask" class="hide_flag">
                </div>
            </div>
            <div id="setting_frame"></div>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script>
            click_cut_url = '{% url "DressApp:click_cut" %}';
            ajax_file_url = '{% url "DressApp:ajax_file_send" %}';//これはjsファイルの読み込みでdjangoのurlタグが解釈されないためあらかじめ変数として作っておく
            select_clothes_url = '{% url "DressApp:select_clothes" %}';
        </script>
        <script src="{% static "app_script/dressed.js" %}"></script>
    </body>
</html>

src/DressApp/templates/dressed.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %} <!-- settings.pyのstaticfileの設定を読み込む -->

<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}dressed{% endblock %}

<!-- main文を設定する -->
{% block contents %}
<!--dressed.cssとの紐付け-->
<link href="{% static "appcss/dressed.css" %}" rel="stylesheet" type="text/css" media="screen and (min-width:376px)">
<link href="{% static "appcss/dressed.css" %}" rel="stylesheet" type="text/css" media="screen and (max-width:375px)">

<div id="main_frame">
    <div id="sub_frame">
        <div id="sub_left">
            <div id="user_img_box">
                <img src="" alt="no_img" id="user_img" class="hide_flag">
            </div>
            <div class="icon">
                <img src="{% static "app_images/dress_img/human.png" %}" alt="no_img" id="human_icon">
            </div>
        </div>
        <div id="sub_right">
            <div class="model"></div>
            <div class="model_have">
                <img src="{% static "app_images/dress_img/model_10.png" %}" alt="no_img" id="1.model_10" class="model_img">
            </div>
            <div class="model_have">
                <img src="{% static "app_images/dress_img/model_9.png" %}" alt="no_img" id="1.model_9" class="model_img">
            </div>
            <div class="model_have">
                <img src="{% static "app_images/dress_img/model_8.png" %}" alt="no_img" id="1.model_8" class="model_img">
            </div>
            <div class="model_have">
                <img src="{% static "app_images/dress_img/model_7.png" %}" alt="no_img" id="1.model_7" class="model_img">
            </div>
            <div class="model_have">
                <img src="{% static "app_images/dress_img/model_6.png" %}" alt="no_img" id="1.model_6" class="model_img">
            </div>
            <div class="model_have">
                <img src="{% static "app_images/dress_img/model_5.png" %}" alt="no_img" id="1.model_5" class="model_img">
            </div>
            <div class="model_have">
                <img src="{% static "app_images/dress_img/model_4.png" %}" alt="no_img" id="1.model_4" class="model_img">
            </div>
            <div class="model_have">
                <img src="{% static "app_images/dress_img/model_2.png" %}" alt="no_img" id="1.model_2" class="model_img">
            </div>
            <div class="model_have">
                <img src="{% static "app_images/dress_img/model_3.png" %}" alt="no_img" id="1.model_3" class="model_img">
            </div>
            <div class="model_have">
                <img src="{% static "app_images/dress_img/model_0.jpeg" %}" alt="no_img" id="1.model_0" class="model_img">
            </div>
            <div class="model_have" id="down">
                <img src="{% static "app_images/dress_img/model_1.png" %}" alt="no_img" id="1.model_1" class="model_img">
            </div>
        </div>
    </div>
    <div id="asset_form" class="hide_flag">
        <div class="avater_icon">
            <img src="{% static "app_images/dress_img/human_plus.png" %}" id="human_plus_icon">
            <div class="avater_text">
                New avater
            </div>
        </div>
        <div class="avater_icon">
            <img src="{% static "app_images/dress_img/human_already.png" %}" alt="no_img" id="human_already_icon">
            <div class="avater_text">
                Avaters
            </div>
        </div>

        <div id="file_form" class="none_flag">
            <form id="ajax-file-send" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <p>
                    <label for="id_human_name">Human name:</label>
                    <input type="text" name="human_name" maxlength="100" required="" id="id_human_name">
                </p>
                <p>
                    <label for="id_height">Height:</label>
                    <input type="number" name="height" value="0" required="" id="id_height"></p>
                <p>
                    <label for="id_picture">Picture:</label>
                    <input type="file" name="picture" accept="image/*" id="id_picture"></p>
                <!--<p>ファイル：<input type="file" id="uploadfile" name="uploadfile" value=""></p>-->
                <p><input type="submit" name="submit"></p>
            </form>
            <!--
            <form enctype="multipart/form-data" action="{% url 'DressApp:upload' %}" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Upload" id="f_b">
            </form>-->
            <!--
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token%}
                {{ form.avator }}{{ form.avator.errors }}
                <button type="submit" class="btn">Register</button>
            </form>-->
                 
            <div id="file_look">

            </div>
            <button class="kyanseru">キャンセル</button>
        </div>
        <div id="avater_select_form" class="none_flag">
            <div id="select_img_contents">
                {% for image in images %}
                <div class="cut_img_contant">
                    <!--<img class="cut_img" src='{{ MEDIA_URL }}{{image.picture}}'>-->
                    <img class="cut_img" src='{{image.cut_image_path}}' id='{{image.id}}' onclick="click_cut_img(this)">
                    <h2 class="cut_img_name">{{ image.human_name }}</h2>
                </div>
                {% endfor %}
            </div>
            <button class="kyanseru">キャンセル</button>
        </div>
    </div>
    <div id="black_pocket">
        <div id="black_mask" class="hide_flag">
        </div>
    </div>
    <div id="load_pocket">
        <div class="load_form none_flag">
            <img src="{% static "app_images/dress_img/hourglass.gif" %}" alt="no_img">
        </div>
        <div class="load_form none_flag">
            <img src="{% static "app_images/dress_img/counter.gif" %}" alt="no_img">
        </div>
    </div>
    <div id="setting_frame"></div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
    click_cut_url = '{% url "DressApp:click_cut" %}';
    ajax_file_url = '{% url "DressApp:ajax_file_send" %}';//これはjsファイルの読み込みでdjangoのurlタグが解釈されないためあらかじめ変数として作っておく
    select_clothes_url = '{% url "DressApp:select_clothes" %}';
</script>
<script src="{% static "app_script/dressed.js" %}"></script>
{% endblock %}

src/DressApp/templates/showall.html
<!DOCTYPE html>
{% load static %} <!-- settings.pyのstaticfileの設定を読み込む -->
<html>
    <head>
        <meta charset="utf-8">
        <title>showall</title>
        <link href="{% static "appcss/dressed.css" %}" rel="stylesheet" type="text/css" media="screen and (min-width:376px)">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <link href="{% static "appcss/dressed.css" %}" rel="stylesheet" type="text/css" media="screen and (max-width:375px)">
    </head>
    <body>
        <h1>Your Human_body</h1>

        {% for image in images %}
            <img src='{{ MEDIA_URL }}{{image.picture}}' width=200>
            <h2>{{ image.human_name }}</h2>
        {% endfor %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    </body>
</html>