src/DressApp/urls.py
from django.urls import path
from . import views

app_name = 'DressApp' # これは、他のテンプレートからviewを呼び出す際に用いるが、この記事では無関係
urlpatterns = [
    path('', views.index, name='index'), #urlに/DressAppと入力するとviews.pyのindex関数が呼び出される。
    #path('chat', views.chat, name='chat'), #urlに/DressAppと入力するとviews.pyのindex関数が呼び出される。
    path('ajax-file-send/', views.ajax_file_send, name='ajax_file_send'),
    path('click_cut/', views.click_cut, name="click_cut"),
    path('select_clothes/', views.select_clothes, name='select_clothes'),
    path('showall/', views.showall, name='showall'),
    path('upload/', views.upload, name='upload')
]

src/accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    
    # サインアップ成功ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),

     # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('login/',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
         ),
    
    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.logoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
]

src/app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
app_name = 'app'
urlpatterns = [
    path('chat',views.index,name='chat'),
    path('customer',views.send_clother,name='clother')
]

src/mainproject/urls.py
from django.contrib import admin
from django.urls import include, path
# auth.viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('app', include('app.urls')),
    path('admin/', admin.site.urls),

    # accounts.urlsへのURLパターンを追加
    path('', include('accounts.urls')),

    # topページ
    path('', include('top.urls')),

    # パスワードリセットのためのURLパターン
    # PasswordResetConfirmViewがプロジェクトのurls.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
           template_name = "password_reset.html"),
         name ='password_reset'),
    
    # メール送信完了ページ
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
           template_name = "password_reset_sent.html"),
         name ='password_reset_done'),
    
    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
           template_name = "password_reset_form.html"),
         name ='password_reset_confirm'),
    
    # パスワードリセット完了ページ
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
           template_name = "password_reset_done.html"),
         name ='password_reset_complete'),
    
    # dress.urlsへのURLパターンを追加
    path('dress/', include('DressApp.urls')),
]

src/top/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'top'
urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
]

src/top/models.py
from django.db import models
import uuid
import django_cleanup
# from imagekit.models import ProcessedImageField
# from imagekit.processors import ResizeToFill
from stdimage.models import StdImageField

# Create your models here.

def image_directory_path(instance, filename):
    return 'images/{}.{}'.format(str(uuid.uuid4()), filename.split('.')[-1])

class Cloth(models.Model):
    # 商品番号 : INTEGR型で、主キー
    number = models.CharField(max_length=100, primary_key=True)
    # 商品名 : 文字列30桁
    name = models.CharField(max_length=200)
    # 性別 : 文字列30桁
    gender = models.CharField(max_length=30)
    # 種類 : 文字列30桁
    kind = models.CharField(max_length=30)
    # サイズ : 文字列30桁
    size = models.CharField(max_length=30)
    # 色 : 文字列30桁
    color = models.CharField(max_length=30)
    #写真のURL
    picture_detail_url = models.URLField(max_length=1000)
    #写真の詳細のURL
    picture_url = models.URLField(max_length=1000)

    # picture = ProcessedImageField(upload_to=image_directory_path,
    #                                        processors=[ResizeToFill(420, 600)],
    #                                        format='JPEG',
    #                                        options={'quality': 60})

    # 画像ファイル
    picture = StdImageField(upload_to=image_directory_path, blank=True, variations={
        'large': (420, 600),
        'medium': (200, 300),
    })



    def __str__(self):
        return self.name

src/top/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Cloth
from django.db.models import Q, query

class IndexView(ListView):
    template_name = 'index.html'
    # model = Cloth
    context_object_name = 'garment_records'
    #queryset = Cloth.objects.filter(color="黒")

    def get_queryset(self):
        queryset = Cloth.objects.order_by('-number')
        keyword = self.request.GET.get('q')

        if keyword:
            queryset = queryset.filter(
                Q(color__icontains=keyword) | Q(kind__icontains=keyword) |
                Q(name__icontains=keyword) | Q(size__icontains=keyword) |
                Q(gender__icontains=keyword)
            )

        return queryset

src/top/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- ヘッダー情報のタイトルを個別に設定できるようにする -->
        <title>{% block title %}{% endblock %}</title>
        
        <!-- アイコン、フォントの読み込み -->
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href={% static 'slick/slick.css' %}>
        <link rel="stylesheet" type="text/css" href={% static 'slick/slick-theme.css' %}>

        <link rel="stylesheet" href={% static "appcss/index.css" %}>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-migrate-3.3.2.min.js" integrity="sha256-Ap4KLoCf1rXb52q+i3p0k2vjBsmownyBTE1EqlRiMwA=" crossorigin="anonymous"></script>
        <script type="text/javascript">
         $(function() {
             var height=$("header").height();
             $("main").css("margin-top", height + 10);
         });
         </script>
        <!-- <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"> -->
        
    </head>
    <body>
        <header>
           <h1>
              <a href="/">CTOs<span class="header_subtitle">customer <div>try on service</div></span></a>
           </h1>
           <nav class="pc-nav">
              <ul>
                <li class="search_box">
                    <form class="search_form" action="#" method="get" autocomplete="off">
                        <input class="search_input" placeholder="search here"  type="search" name="q" value="{{ request.Get.query }}">
                        <input class="search_btn fas fa-search" type="submit" value="&#xf002;">
                    </form>
                </li>
                <li><a href="{% url 'accounts:login' %}"><i class="fas fa-user-alt"></i></a></li>
              </ul>
           </nav>
        </header>
        <!-- メインコンテンツ -->
        <main>
            <!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む -->
            {% block contents %}{% endblock %}
        </main>
        <script src={% static 'slick/slick.min.js' %}></script>
        <script src={% static 'app_script/index.js' %}></script>
     </body>
</html>

src/top/templates/index.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
{% load static %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Online Try On Service{% endblock %}

      {% block contents %}
      <ul class="slider">
            {% for record in garment_records %}
            <div class="img_back">
                  <li>
                        <img src="{{record.picture.large.url}}" alt="">
                        <span>
                              <a href="{% url 'DressApp:index' %}" class="tryon_link image_link">オンライン試着</a>
                              <a href="{{record.picture_detail_url}}" class="website_link image_link">website</a>
                        </span>
                  </li>
            </div>
            {% endfor %}
      </ul>
      
      {% endblock %}

src/top/templates/list.html
{% if cloth %}
<ul>
    {% for item in cloth %}
    <li>{{ item.name }}</li>
    <li>{{ item.color }}</li>
    <li>{{ item.kind }}</li>
    <li>{{ item.number }}</li>
    <li>{{ item.size }}</li>
    <li>{{ item.pictures }}</li>
    <img src="{{item.img.url}}">
    {% endfor %}
</ul>
{% endif %}